import Head from "next/head";

// local imports
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Intro from "../components/Intro";
import Technologies from "../components/Technologies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pranav Mishra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Intro />
        <About />
        <Technologies />
        <Contact />
      </main>
    </div>
  );
}
